# Generated by Django 2.0.13 on 2019-07-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190706_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videolink',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
