# Generated by Django 2.0.13 on 2019-07-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_videolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fav',
            field=models.BooleanField(default=True),
        ),
    ]
